/// A writer for the Venom Advanced Exchange Protocol (VAXP) format.
class VaxpWriter {
  /// Converts a flat Map with dot-notation keys back into a VAXP string.
  ///
  /// Example input:
  /// { "system.theme_mode": "dark", "apps.terminal.font_size": 14 }
  ///
  /// Example output:
  /// SECTION system {
  ///   theme_mode: "dark";
  /// }
  /// SECTION apps.terminal {
  ///   font_size: 14;
  /// }
  String stringify(Map<String, dynamic> data) {
    final buffer = StringBuffer();
    buffer.writeln('// Venom Advanced Exchange Protocol (VAXP)');
    buffer.writeln('// Auto-generated by Venom Config System');
    buffer.writeln();

    // Group by section
    final Map<String, Map<String, dynamic>> sections = {};

    for (var entry in data.entries) {
      final parts = entry.key.split('.');
      if (parts.length < 2) continue; // Skip invalid keys

      // The section is everything up to the last part
      // e.g. "apps.terminal.font_size" -> section: "apps.terminal", key: "font_size"
      final sectionName = parts.sublist(0, parts.length - 1).join('.');
      final keyName = parts.last;

      sections.putIfAbsent(sectionName, () => {});
      sections[sectionName]![keyName] = entry.value;
    }

    // Write sections
    for (var sectionName in sections.keys) {
      buffer.writeln('SECTION $sectionName {');
      final sectionData = sections[sectionName]!;

      for (var key in sectionData.keys) {
        final value = sectionData[key];
        buffer.writeln('    $key: ${_formatValue(value)};');
      }

      buffer.writeln('}');
      buffer.writeln();
    }

    return buffer.toString();
  }

  String _formatValue(dynamic value) {
    if (value is String) {
      return '"$value"';
    }
    return value.toString();
  }
}
